# Generated by Django 3.2 on 2022-09-13 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('img', models.ImageField(upload_to='Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('img', models.ImageField(upload_to='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Proudct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('sku', models.IntegerField(verbose_name='SKU')),
                ('price', models.FloatField(verbose_name='Price')),
                ('flag', models.CharField(choices=[('new', 'new'), ('sale', 'sale'), ('feature', 'feature')], max_length=15, verbose_name='Flag')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Subtitle')),
                ('describtion', models.TextField(max_length=10000, verbose_name='Describtion')),
                ('date_publish', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('video', models.URLField(blank=True, null=True, verbose_name='Video')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_Brand', to='proudct.brand', verbose_name='Brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='proudct.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProudctReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('review', models.CharField(max_length=300, verbose_name='Review')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proudct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product', to='proudct.proudct', verbose_name='Proudct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProudctImge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ProudctImge', verbose_name='Image')),
                ('proudct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_product', to='proudct.proudct', verbose_name='Proudct')),
            ],
        ),
    ]
