# Generated by Django 3.2 on 2022-09-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proudct', '0003_auto_20220916_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proudct',
            name='img',
            field=models.ImageField(upload_to='ProudctImge/', verbose_name='Image'),
        ),
    ]
