# Generated by Django 3.2 on 2022-09-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proudct', '0004_alter_proudct_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proudct',
            name='img',
            field=models.ImageField(upload_to='proudct/', verbose_name='Image'),
        ),
    ]
