# Generated by Django 3.2 on 2022-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proudct', '0006_alter_proudct_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterModelManagers(
            name='proudct',
            managers=[
            ],
        ),
    ]
