# Generated by Django 3.2 on 2022-09-27 15:23

from django.db import migrations, models
import utils.generatr_code


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220927_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default=utils.generatr_code.generate_code, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='used_code',
            field=models.BooleanField(default=False),
        ),
    ]
