# Generated by Django 3.2 on 2022-09-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('call_us', models.CharField(max_length=15)),
                ('email_us', models.EmailField(max_length=254)),
                ('email', models.TextField(max_length=200)),
                ('phone', models.TextField(max_length=200)),
                ('adress', models.TextField(max_length=400)),
                ('fb_link', models.URLField(max_length=300)),
                ('instagram_link', models.URLField(max_length=300)),
                ('tw_link', models.URLField(max_length=300)),
                ('pentrist_link', models.URLField(max_length=300)),
            ],
        ),
    ]
