# Generated by Django 3.2 on 2022-11-10 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.generatr_code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proudct', '0007_auto_20221008_1406'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=utils.generatr_code.generate_code, max_length=8)),
                ('status', models.CharField(choices=[('recieved', 'recieved'), ('processed', 'processed'), ('shipped', 'shipped'), ('delivered', 'delivered')], max_length=10)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('delvery_time', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=80, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantiy', models.IntegerField(max_length=10)),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('slug', models.SlugField(blank=True, editable=False, max_length=80, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='orders.order')),
                ('proudct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proudct_order', to='proudct.proudct')),
            ],
        ),
    ]
