# Generated by Django 3.2 on 2022-11-14 12:08

from django.db import migrations, models
import utils.generatr_code


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartdetail_quantiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='code',
            field=models.CharField(default=utils.generatr_code.generate_code_orderes, max_length=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default=utils.generatr_code.generate_code_orderes, max_length=8),
        ),
    ]
