# Generated by Django 3.2 on 2022-11-15 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20221114_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuopon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('quantiy', models.IntegerField()),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuopon',
                'verbose_name_plural': 'Cuopons',
            },
        ),
    ]
