# Generated by Django 3.2 on 2022-11-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cuopon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuopon',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
